### ISSUE TITLE
1.18.2 -6.1 Incompat with Voluminous Energy

### ISSUE THREAD

**Issue by Daihok41** [MrScautHD/Beyond-Earth#108]
Like titale says 1.18.2-6.1 version of Beyond Earth is incompatable with Voluminous energy can have both in pack and server load fine and client loads fine but client crashs out when try and connect to server. No crash report just crashs back to menu screen. I reported issue to Voluminous energy as well. He thinks maybe on you guys end but have reported to both places now

**Comment by Eelt** [comment]
I have actually traced this crash issue down to a differed packet buffer read in Voluminous Energy's

**Comment by Eelt** [comment]
I have actually traced this connection issue due to a differed packet buffer read in one of Voluminous Energy's recipe's `fromNetwork` method. This is a Voluminous Energy issue and has been fixed with a new build of Voluminous Energy.
This issue can be closed (both fixed and not on Beyond Earth's end).
