### ISSUE TITLE
Literally can not see anything when night.

### ISSUE THREAD

**Issue by David3118** [MrScautHD/Beyond-Earth#254]
### Mod loader

Forge

### Minecraft version

1.19.4

### Beyond Earth version

6.5

### Modloader version

Forge: 45.1.0

### The latest.log file

https://gist.github.com/David3118/bec47a9384936dc71646700653d3554c

### Issue description

Whenever I activate this mod, my entire world turns a "blueish" hue, and when it becomes dark, visibility is severely compromised. Torches provide no assistance as mobs appear even brighter than they should be... I checked every mod and every resource pack.

### Steps to reproduce

1. Boot up the world
2. Spawn torch
3.Set time to night and place torch

**Comment by glowiak** [comment]
Spawn torch?

**Comment by st0x0ef** [comment]
Can I have the log file pls?

**Comment by MrScautHD** [comment]
Not Beyond-Earth's fault.

**Comment by Contrean** [comment]
Hey,
I also have this bug. I've tried and tested different aproaches, but didn't manage to achieve anything.

**Modversion**: All Snapshot versions for 1.20.1 (01, 02, 03)

**Modloader**: Forge - Versions 1.20.1 - 47.2.1 (Latest) and 1.20.1 - 47.2.0 (Recommended)

While testing, I had no other mods installed.

I have added the debug-log and the latest-log, if needed.
[debug.log](https://github.com/MrScautHD/Beyond-Earth/files/13221858/debug.log)
[latest.log](https://github.com/MrScautHD/Beyond-Earth/files/13221859/latest.log)

I myself wasn't able to find anything in there, but my java knowledge is very basic.

I know you've commented 'Not Beyond-Earth's fault', but since I only have that problem, if I use Beyond-Earth, I don't see any other causes.
