### ISSUE TITLE
List of possible issues found in version 6.0b

### ISSUE THREAD

**Issue by DDaMAGEr** [MrScautHD/Beyond-Earth#52]
Mars Ice Shard Ore uses word "Moon" twice in oregen, which makes it check if a block is Moon Stone, and since that doesn't generate on Mars - Mars Ice Shard Ore never generates as a result.
Venus Bullets do not seem to be generating at all.
Space Boots and Oxygen Mask give +4 to armor, which can go over limit on certain sets, and bigger than Netherite Space Armor whose give +3.
Mars Stone Brick Slabs, Venus Stone Brick Slabs, Venus Sandstone Brick Slabs, Mercury Stone Brick Slabs do not drop themselves when broken with a pickaxe.
Moglers are not fire resistant (logically they should be).
After travelling using rocket Experience bar is locked (shows 0 exp) until you get one experience point, travel to another dimension or relog (this locks enchanting, other stuff).
[IMPORTANT] When Water Pump tries to absorb water from a block occupied by Kelp or Sea Grass - this will produce a crash and world lock.
Gravity on another planets behaves in a quite strange way to the point it almost never registers significant fall damage - resulting almost impossible to die from falling no matter how high the height is.
Unlit (Coal) Lantern has very long breaking time comparing to normal lantern (and doesn't have tag "mineable with pickaxe").
Extraterrestrial mobs seem to be able to spawn on almost anything (including slabs/glass/leaves).
After landing module explodes due to bad landing - a rocket is dropped as an item and can be retrieved.

...

In the End dimension or Nether rooftop rockets can be used to enter outer space, showing earth-like attitude bar (is that intended?).
Netherite Space Armor does not have armor hardness (maybe not an issue).
Moglers can only be found on top on Venus Towers (maybe not an issue) - maybe they could also spawn on nighttime/caves on Venus to make it harder.
Pygros run away on fear from Soul Fire-related blocks (l think that shouldn't happen because these blocks are everywhere in their dwellings).
(more like suggestion) Pygros do not react when Ancient Debris, Lodestones or Netherite Blocks are broken next to them (maybe make them aggro to make it harder).
Rockets just stop when hit ceiling (no explosion/something).
Unlit (Coal) Torch crafting recipe yields 1 unlit torch from a 1 stick, 1 coal and 1 paper, while normal torch recipe yields 4 torches from 1 coal, 1 stick.
On Mars Overworld-like Fossils with coal ore and deepslate diamond ore blocks in them can be found, although this may be intentional.
Water exposed directly to sky on Moon or Mars does not freeze despite values shown in desc are subzero.

**Comment by MrScautHD** [comment]
not all is a bug but i want to fix and add features like rocket explosion if it fly to a ceiling ...

**Comment by MrScautHD** [comment]
Space Boots and Oxygen Mask give +4 to armor, which can go over limit on certain sets, and bigger than Netherite Space Armor whose give +3. ✅

Mars Stone Brick Slabs, Venus Stone Brick Slabs, Venus Sandstone Brick Slabs, Mercury Stone Brick Slabs do not drop themselves when broken with a pickaxe. ✅

After travelling using rocket Experience bar is locked (shows 0 exp) until you get one experience point, travel to another dimension or relog (this locks enchanting, other stuff). ✅

[IMPORTANT] When Water Pump tries to absorb water from a block occupied by Kelp or Sea Grass - this will produce a crash and world lock. ✅

Unlit (Coal) Lantern has very long breaking time comparing to normal lantern (and doesn't have tag "mineable with pickaxe"). ✅

After landing module explodes due to bad landing - a rocket is dropped as an item and can be retrieved. ✅

Netherite Space Armor does not have armor hardness (maybe not an issue). ✅

Pygros run away on fear from Soul Fire-related blocks (l think that shouldn't happen because these blocks are everywhere in their dwellings). ✅

Water exposed directly to sky on Moon or Mars does not freeze despite values shown in desc are subzero. ✅

**Comment by MrScautHD** [comment]
i fixed now the bugs that i not kowed before, the other bugs and features are we adding with 6.1
