### ISSUE TITLE
[1.18.1][6.0c]Crash on start

### ISSUE THREAD

**Issue by BarbaDaBietola** [MrScautHD/Beyond-Earth#62]
The game doesn't start, giving this crash error:
"The game crashed whilst rendering overlay
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Codice di uscita: -1"

**Comment by MrScautHD** [comment]
witch forge version?

**Comment by MarkusBordihn** [comment]
I got the same issue and it was related to OptiFine which used and outdated mixin for Forge 39.0.0. and cause this mod to crash.
If you are using OptiFine (OptiFine HD U H5 pre4 or so), please try if it works without OptiFine.

**Comment by Chaos4Link** [comment]
Yes, it works without Optifine, had the same issue with newer Forge versions

**Comment by MrScautHD** [comment]
Pls use 59 and higher

**Comment by MarkusBordihn** [comment]
Just for clarification, the problem is that OptiFine is using a 39.0.0 mapping which is not working with any mod which is using the newer .59 mapping and has an overlapping mixins.

As long you are not using any OptiFine overwritten mixed function with the newer signature it's fine, but as soon any mod try to use it, it will get a MixinTransformerError.

The only way to solve this is to use a newer OptiFine version (which is not released yet) or to avoid such problematic mixing (if possible).
